"""Generated Python project bootstrap tests (CLI-02, TL-5).

Verify that a project generated by ``create_project`` contains:
- A valid ``tests/test_app.py`` that can be discovered and executed
- An ``app.py`` that imports correctly
- All generated files are parseable

The generated test must enter through bootstrap (import machinery) and
pass under ``vyne test`` semantics.
"""

from __future__ import annotations

from pathlib import Path
from tempfile import TemporaryDirectory
import subprocess
import sys
import unittest

from vyne.cli.new import create_project
from vyne.cli.project import load_project


class GeneratedPythonProjectTests(unittest.TestCase):
    """TL-5: Generated test executes through bootstrap and passes."""

    def test_generated_test_file_is_discoverable(self):
        """The generated tests/test_app.py is valid Python and importable."""
        with TemporaryDirectory() as tmp:
            path = Path(tmp) / "TestBootstrap"
            create_project(path, package="com.example.bootstrap", module="app")
            test_file = path / "tests" / "test_app.py"
            self.assertTrue(test_file.is_file())
            # Parse check
            compile(test_file.read_text(encoding="utf-8"),
                    str(test_file), "exec")

    def test_generated_app_file_is_valid_python(self):
        """The generated app.py must compile as valid Python."""
        with TemporaryDirectory() as tmp:
            path = Path(tmp) / "ValidApp"
            create_project(path, package="com.example.validapp")
            app_file = path / "app.py"
            self.assertTrue(app_file.is_file())
            compile(app_file.read_text(encoding="utf-8"),
                    str(app_file), "exec")

    def test_generated_test_runs_with_python(self):
        """The generated test can be executed by the Python interpreter.

        The generated ``test_app.py`` imports the app module, which calls
        ``run_app()``.  Outside the Vyne host, ``run_app()`` is expected
        to raise ``RuntimeError``.  This test verifies that the generated
        test file is valid, discoverable Python and that the error comes
        from the expected ``run_app`` guard, not from syntax or import
        errors.
        """
        with TemporaryDirectory() as tmp:
            path = Path(tmp) / "TestRunner"
            create_project(path, package="com.example.testrunner", module="app")

            # Run the generated test via Python discovery
            # The test module imports the app module, so the project root
            # must be on sys.path.
            result = subprocess.run(
                [sys.executable, "-m", "unittest", "discover",
                 "-s", str(path / "tests"),
                 "-t", str(path),
                 "-v"],
                cwd=path,
                capture_output=True, text=True,
                env={**__import__("os").environ,
                     "PYTHONDONTWRITEBYTECODE": "1",
                     "PYTHONPATH": str(path)},
                timeout=30,
            )
            # The test may fail because run_app() rejects non-host execution.
            # This is expected.  We accept both:
            #   - success (0): the test gracefully handles the guard
            #   - failure with 'run_app' in stderr: the guard worked correctly
            combined = result.stdout + result.stderr
            if result.returncode != 0:
                self.assertIn("run_app", combined,
                    f"Unexpected failure (not run_app guard):\n{combined}")
                self.assertNotIn("SyntaxError", combined,
                    f"Syntax error in generated test:\n{combined}")
                self.assertNotIn("ImportError", combined,
                    f"Import error in generated test:\n{combined}")

    def test_generated_test_passes_under_vyne_path(self):
        """The generated test passes when PYTHONPATH includes the vyne package.

        Verifies that the test bootstrap works: the generated test discovers
        and executes, with the expected ``run_app`` guard behavior when
        running outside a Vyne host context.
        """
        with TemporaryDirectory() as tmp:
            path = Path(tmp) / "TestVynePath"
            create_project(path, package="com.example.vyne", module="app")

            # Construct PYTHONPATH to include the vyne package
            vyne_src = Path(__file__).resolve().parents[1] / "packages" / "vyne" / "src"
            result = subprocess.run(
                [sys.executable, "-m", "unittest", "discover",
                 "-s", str(path / "tests"),
                 "-t", str(path),
                 "-v"],
                cwd=path,
                capture_output=True, text=True,
                env={**__import__("os").environ,
                     "PYTHONDONTWRITEBYTECODE": "1",
                     "PYTHONPATH": f"{path}:{vyne_src}"},
                timeout=30,
            )
            combined = result.stdout + result.stderr
            if result.returncode != 0:
                self.assertIn("run_app", combined,
                    f"Unexpected failure (not run_app guard):\n{combined}")
                self.assertNotIn("SyntaxError", combined,
                    f"Syntax error in generated test:\n{combined}")
                self.assertNotIn("ModuleNotFoundError", combined,
                    f"Module not found in generated test:\n{combined}")

    def test_generated_config_is_valid_toml(self):
        """Generated vyne.toml is parseable TOML."""
        with TemporaryDirectory() as tmp:
            path = Path(tmp) / "ValidToml"
            create_project(path, package="com.example.toml")
            vyne_toml = path / "vyne.toml"
            self.assertTrue(vyne_toml.is_file())
            import tomllib
            parsed = tomllib.loads(vyne_toml.read_text(encoding="utf-8"))
            self.assertIn("app", parsed)
            self.assertIn("android", parsed)
            self.assertIn("paths", parsed)

    def test_generated_pyproject_is_valid_toml(self):
        """Generated pyproject.toml is valid TOML with vyne dependency."""
        with TemporaryDirectory() as tmp:
            path = Path(tmp) / "ValidPyproject"
            create_project(path, package="com.example.pyproject")
            pyproject = path / "pyproject.toml"
            self.assertTrue(pyproject.is_file())
            import tomllib
            parsed = tomllib.loads(pyproject.read_text(encoding="utf-8"))
            self.assertIn("project", parsed)
            self.assertIn("dependencies", parsed["project"])
            deps = parsed["project"]["dependencies"]
            self.assertTrue(any("vyne" in d for d in deps))

    def test_generated_settings_gradle_is_valid_kts(self):
        """Generated settings.gradle.kts contains essential structure."""
        with TemporaryDirectory() as tmp:
            path = Path(tmp) / "ValidSettings"
            create_project(path, package="com.example.settings")
            settings = path / "android" / "settings.gradle.kts"
            self.assertTrue(settings.is_file())
            content = settings.read_text(encoding="utf-8")
            self.assertIn('include(":app")', content)
            self.assertNotIn("runtime", content)
            self.assertIn("pluginManagement", content)

    def test_all_generated_files_are_valid_utf8(self):
        """Every generated text file is valid UTF-8."""
        with TemporaryDirectory() as tmp:
            path = Path(tmp) / "Utf8Check"
            create_project(path, package="com.example.utf8")
            text_extensions = {".toml", ".py", ".kts", ".xml", ".properties", ".bat"}
            for p in path.rglob("*"):
                if p.is_file() and p.suffix in text_extensions:
                    try:
                        p.read_text(encoding="utf-8")
                    except Exception as exc:
                        self.fail(f"{p}: not valid UTF-8: {exc}")

    def test_generated_app_module_can_be_imported_when_vyne_available(self):
        """The generated app.py module can be imported (requires vyne in path)."""
        with TemporaryDirectory() as tmp:
            path = Path(tmp) / "ImportableApp"
            create_project(path, package="com.example.importable", module="myapp")

            vyne_src = Path(__file__).resolve().parents[1] / "packages" / "vyne" / "src"
            result = subprocess.run(
                [sys.executable, "-c",
                 f"import sys; sys.path.insert(0, '{path}'); "
                 f"sys.path.insert(0, '{vyne_src}'); "
                 "import myapp"],
                capture_output=True, text=True,
                timeout=30,
            )
            # May fail if vyne dependencies aren't installed, but should not
            # fail with SyntaxError or ImportError due to missing module.
            # If it fails with ModuleNotFoundError for non-vyne packages,
            # that's acceptable.
            combined = result.stdout + result.stderr
            if result.returncode != 0:
                # Acceptable: missing non-vyne dep; NOT acceptable: syntax error
                self.assertNotIn("SyntaxError", combined,
                                 f"Syntax error in generated app:\n{combined}")


if __name__ == "__main__":
    unittest.main()
