"""Generated project template constants — DO NOT EDIT.

This file is generated by ``scripts/generate_project_templates.py``.
Edit that script instead; run it with ``--check`` to verify drift.
"""

from __future__ import annotations

# fmt: off
# isort: skip_file


PYTHON_VERSION = '3.14'
DEFAULT_COMPILE_SDK = 35
DEFAULT_TARGET_SDK = 35
DEFAULT_MIN_SDK = 26
DEFAULT_VERSION = '0.1.0'
DEFAULT_VERSION_CODE = 1

AGP_VERSION = '8.7.3'
KOTLIN_VERSION = '2.0.21'
JAVA_TARGET = '17'
ANDROIDX_ANNOTATION_VERSION = '1.9.1'
CHAQUOPY_VERSION = '17.0.0'

MIN_SDK_MINIMUM = 26

GRADLE_PROPERTIES = 'android.useAndroidX=true\nandroid.nonTransitiveRClass=true\norg.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8\n'

ROOT_BUILD_GRADLE = """\
plugins {
    id("com.android.application") version "8.7.3" apply false
    id("org.jetbrains.kotlin.android") version "2.0.21" apply false
    id("com.chaquo.python") version "17.0.0" apply false
}
"""

APP_BUILD_GRADLE = """\
plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
    id("com.chaquo.python")
}

val appId = providers.gradleProperty("vyne.applicationId").orElse("com.example.vyneapp").get()
val appLabel = providers.gradleProperty("vyne.appLabel").orElse("Vyne App").get()
val appModule = providers.gradleProperty("vyne.appModule").orElse("app").get()
val appSourceFile = file(providers.gradleProperty("vyne.appSource").orElse("app.py").get())
val frameworkPythonDir = file(providers.gradleProperty("vyne.frameworkPythonDir").orElse("../../packages/vyne/src").get())
val hostSourceDir = file(providers.gradleProperty("vyne.hostSourceDir").orElse("../../android/host/src/main/java").get())
val hostResDir = file(providers.gradleProperty("vyne.hostResDir").orElse("../../android/host/src/main/res").get())
val extensionKotlinDirs = providers.gradleProperty("vyne.extensionKotlinDirs").orElse("").get().split(":").filter { it.isNotBlank() }
val extensionResDirs = providers.gradleProperty("vyne.extensionResDirs").orElse("").get().split(":").filter { it.isNotBlank() }
val extensionPythonDirs = providers.gradleProperty("vyne.extensionPythonDirs").orElse("").get().split(":").filter { it.isNotBlank() }
val minSdkValue = providers.gradleProperty("vyne.minSdk").orElse("26").get().toInt()
val targetSdkValue = providers.gradleProperty("vyne.targetSdk").orElse("35").get().toInt()
val compileSdkValue = providers.gradleProperty("vyne.compileSdk").orElse("35").get().toInt()

android {
    namespace = appId
    compileSdk = compileSdkValue

    defaultConfig {
        applicationId = appId
        minSdk = minSdkValue
        targetSdk = targetSdkValue
        versionCode = providers.gradleProperty("vyne.versionCode").orElse("1").get().toInt()
        versionName = providers.gradleProperty("vyne.versionName").orElse("1.0").get()
        manifestPlaceholders["vyneAppLabel"] = appLabel
        manifestPlaceholders["vyneAppModule"] = appModule

        ndk {
            abiFilters += listOf("arm64-v8a", "x86_64")
        }

    }

    sourceSets {
        getByName("main") {
            java.srcDir(hostSourceDir)
            res.srcDir(hostResDir)
            extensionKotlinDirs.forEach { java.srcDir(it) }
            extensionResDirs.forEach { res.srcDir(it) }
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = "17"
    }

    aaptOptions.ignoreAssetsPattern = "android-vyne-dont-ignore-anything"
}

chaquopy {
    defaultConfig {
        version = "3.14"
    }
    sourceSets {
        getByName("main") {
            srcDir(frameworkPythonDir)
            srcDir(appSourceFile.parentFile)
            extensionPythonDirs.forEach { srcDir(it) }
            exclude("android/**", ".venv/**", "tests/**", "**/__pycache__/**")
        }
    }
}

dependencies {
    implementation("androidx.annotation:annotation:1.9.1")
}
"""

SETTINGS_GRADLE = """\
pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "{name}"
include(":app")
"""

ANDROID_MANIFEST = """\
<manifest xmlns:android="http://schemas.android.com/apk/res/android">
    <application
        android:name="com.chaquo.python.android.PyApplication"
        android:allowBackup="true"
        android:label="${vyneAppLabel}"
        android:supportsRtl="true"
        android:theme="@style/AppTheme">
        <meta-data
            android:name="dev.vyne.MODULE_NAME"
            android:value="${vyneAppModule}" />
        <activity
            android:name="dev.vyne.MainActivity"
            android:exported="true"
            android:launchMode="singleTop"
            android:configChanges="orientation|screenSize">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    </application>
</manifest>
"""
