"""Extension discovery, validation, and build-time generation.

Extensions are developer-written bundles discovered by convention:
``extensions/<name>/extension.toml`` at the project root (sorted by name;
the directory name is the extension identity). Each extension contributes:

- ``python/`` — Python modules, packaged into the APK. The APP imports
  them itself (constructors, launch functions) — the framework provides
  tools, not wiring.
- ``android/`` — Kotlin source root compiled into the app module.
- ``res/`` (optional) — Android resource root.

``vyne build`` regenerates one file per project (journaled, byte-identical
skip): ``ExtensionRegistrant.kt``, which calls each extension's
``register(context, registry)``. In a generated project it lands in the
app's own java source set (the packaged host excludes its shipped default,
so exactly one declaration exists per module); in the framework checkout it
overwrites the host's default in place.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
import os
import re
import tomllib
from typing import Any

from vyne.cli.generation import ConflictPolicy, PlanBuilder

_FQN_RE = re.compile(r"^[a-zA-Z_][a-zA-Z0-9_]*\.([a-zA-Z_][a-zA-Z0-9_]*\.)*[a-zA-Z_][a-zA-Z0-9_]*$")
REGISTRANT_RELATIVE = "ExtensionRegistrant.kt"


def is_valid_identifier(name: str) -> bool:
    """A valid, non-keyword Python identifier."""
    from keyword import iskeyword
    return name.isidentifier() and not iskeyword(name)


@dataclass(frozen=True)
class Extension:
    """One validated extension discovered at the project root."""

    name: str
    root: Path
    python_dir: Path
    kotlin_dir: Path
    res_dir: Path | None
    android_register: str


def discover_extensions(project_root: Path) -> list[Extension]:
    """Return every valid extension under ``extensions/*``, sorted by name.

    Raises RuntimeError with a precise diagnostic for any broken extension —
    a broken extension must fail the build, never silently vanish.
    """
    extensions_dir = project_root / "extensions"
    if not extensions_dir.is_dir():
        return []
    discovered: list[Extension] = []
    for manifest in sorted(extensions_dir.glob("*/extension.toml")):
        name = manifest.parent.name
        discovered.append(_load_extension(name, manifest))
    return discovered


def _load_extension(dir_name: str, manifest: Path) -> Extension:
    raw = _parse_manifest(manifest)
    if not is_valid_identifier(dir_name):
        raise RuntimeError(
            f"{manifest}: extension directory name {dir_name!r} is not a "
            "valid Python identifier"
        )
    register_fqn = _exact_str(raw, "android_register", manifest)
    if not _FQN_RE.match(register_fqn):
        raise RuntimeError(
            f"{manifest}: android_register {register_fqn!r} is not a valid "
            f"fully-qualified Kotlin object name"
        )

    root = manifest.parent
    python_dir = root / "python"
    if not python_dir.is_dir():
        raise RuntimeError(f"{manifest}: missing python/ directory")
    kotlin_dir = root / "android"
    if not kotlin_dir.is_dir():
        raise RuntimeError(f"{manifest}: missing android/ directory")
    res_dir = root / "res"
    if not res_dir.is_dir():
        res_dir = None

    return Extension(
        name=dir_name,
        root=root,
        python_dir=python_dir,
        kotlin_dir=kotlin_dir,
        res_dir=res_dir,
        android_register=register_fqn,
    )


def _parse_manifest(manifest: Path) -> dict[str, Any]:
    try:
        raw = tomllib.loads(manifest.read_text(encoding="utf-8"))
    except (OSError, tomllib.TOMLDecodeError) as exc:
        raise RuntimeError(f"Cannot parse {manifest}: {exc}") from exc
    if not isinstance(raw, dict):
        raise RuntimeError(f"{manifest}: extension.toml must be a table")
    return raw


def _exact_str(raw: dict[str, Any], key: str, manifest: Path) -> str:
    value = raw.get(key)
    if not isinstance(value, str) or not value:
        raise RuntimeError(f"{manifest}: {key!r} must be a non-empty string")
    return value


# ---------------------------------------------------------------------------
# Generation
# ---------------------------------------------------------------------------

def registrant_content(extensions: list[Extension]) -> str:
    """The generated Kotlin registrant for the given extensions."""
    calls = "\n".join(
        f"    {ext.android_register}.register(context, registry)"
        for ext in extensions
    )
    if calls:
        calls += "\n"
    surface_calls = "\n".join(
        f"    ({ext.android_register} as? SurfaceRegistrant)"
        f"?.registerSurfaces(registry)"
        for ext in extensions
    )
    if surface_calls:
        surface_calls += "\n"
    return f"""/** Generated by the Vyne CLI. DO NOT EDIT. */
package dev.vyne.generated

import android.content.Context
import dev.vyne.ElementRegistry
import dev.vyne.RenderSurfaceRegistry
import dev.vyne.SurfaceRegistrant

internal fun registerAppExtensions(
    context: Context,
    registry: ElementRegistry,
) {{
{calls}}}

internal fun registerAppSurfaces(
    registry: RenderSurfaceRegistry,
) {{
{surface_calls}}}
"""


def registrant_target(project: Any) -> Path:
    """The registrant file path for the project mode.

    The app module owns the generated file (the packaged host excludes its
    shipped default); the checkout host regenerates its own in place.
    """
    if project.generated:
        return (
            project.root / "android" / "app" / "src" / "main" / "java"
            / "dev" / "vyne" / "generated" / REGISTRANT_RELATIVE
        )
    return (
        project.root / "android" / "host" / "src" / "main" / "java"
        / "dev" / "vyne" / "generated" / REGISTRANT_RELATIVE
    )


def generate_extension_files(project: Any, extensions: list[Extension]) -> None:
    """Journaled generation of the registrant.

    Written through the durable generation transaction; byte-identical
    content skips the write (no churn on unchanged builds).
    """
    registrant_path = registrant_target(project)
    builder = PlanBuilder(project.root)
    builder.add_file(
        os.path.relpath(registrant_path, project.root),
        registrant_content(extensions),
        policy=ConflictPolicy.REPLACE,
    )
    plan = builder.preflight()
    plan.apply()
    plan.cleanup()
