"""Material 3 Expressive widgets for Vyne.

The ``MATERIAL3_CATALOG`` mapping is kept in the same order as the live
Material 3 component catalog.  It provides a machine-checkable coverage index
for the component families implemented by this package.
"""

from vyne.material.components import (
    Badge,
    Badged,
    BottomAppBar,
    BottomSheet,
    Button,
    ButtonGroup,
    ButtonGroupItem,
    Card,
    Carousel,
    Checkbox,
    Chip,
    CircularProgressIndicator,
    DatePicker,
    DateRangePicker,
    Dialog,
    ExtendedFloatingActionButton,
    FabMenuItem,
    FloatingActionButton,
    FloatingActionButtonMenu,
    FloatingToolbar,
    IconButton,
    LinearProgressIndicator,
    LinearWavyProgressIndicator,
    ListItem,
    LoadingIndicator,
    MaterialDivider,
    MaterialList,
    Menu,
    MenuItem,
    NavigationBar,
    NavigationDrawer,
    NavigationItem,
    NavigationRail,
    RadioButton,
    RangeSlider,
    SearchBar,
    SegmentedButton,
    SegmentedButtonGroup,
    SegmentedItem,
    SideSheet,
    Slider,
    Snackbar,
    SplitButton,
    Switch,
    Tab,
    TabItem,
    Tabs,
    TextField,
    TimePicker,
    Toolbar,
    Tooltip,
    TopAppBar,
)
from vyne.material.theme import (
    ColorScheme,
    DEFAULT_THEME,
    MaterialTheme,
    ShapeScale,
    Typography,
    TypeStyle,
)


MATERIAL3_CATALOG: dict[str, tuple[str, ...]] = {
    "app-bars": ("TopAppBar", "BottomAppBar"),
    "badges": ("Badge", "Badged"),
    "bottom-sheets": ("BottomSheet",),
    "button-groups": ("ButtonGroup",),
    "buttons": ("Button",),
    "cards": ("Card",),
    "carousel": ("Carousel",),
    "checkbox": ("Checkbox",),
    "chips": ("Chip",),
    "date-pickers": ("DatePicker", "DateRangePicker"),
    "dialogs": ("Dialog",),
    "divider": ("MaterialDivider",),
    "extended-fab": ("ExtendedFloatingActionButton",),
    "fab-menu": ("FloatingActionButtonMenu",),
    "floating-action-button": ("FloatingActionButton",),
    "icon-buttons": ("IconButton",),
    "lists": ("MaterialList", "ListItem"),
    "loading-indicator": ("LoadingIndicator",),
    "menus": ("Menu",),
    "navigation-bar": ("NavigationBar",),
    "navigation-drawer": ("NavigationDrawer",),
    "navigation-rail": ("NavigationRail",),
    "progress-indicators": (
        "CircularProgressIndicator",
        "LinearProgressIndicator",
        "LinearWavyProgressIndicator",
    ),
    "radio-button": ("RadioButton",),
    "search": ("SearchBar",),
    "segmented-buttons": ("SegmentedButton", "SegmentedButtonGroup"),
    "side-sheets": ("SideSheet",),
    "sliders": ("Slider", "RangeSlider"),
    "snackbar": ("Snackbar",),
    "split-button": ("SplitButton",),
    "switch": ("Switch",),
    "tabs": ("Tab", "Tabs"),
    "text-fields": ("TextField",),
    "time-pickers": ("TimePicker",),
    "toolbars": ("Toolbar", "FloatingToolbar"),
    "tooltips": ("Tooltip",),
}

# Within the material namespace, ``Divider`` is the themed component.
Divider = MaterialDivider


__all__ = [
    "Badge",
    "Badged",
    "BottomAppBar",
    "BottomSheet",
    "Button",
    "ButtonGroup",
    "ButtonGroupItem",
    "Card",
    "Carousel",
    "Checkbox",
    "Chip",
    "CircularProgressIndicator",
    "ColorScheme",
    "DatePicker",
    "DateRangePicker",
    "DEFAULT_THEME",
    "Dialog",
    "Divider",
    "ExtendedFloatingActionButton",
    "FabMenuItem",
    "FloatingActionButton",
    "FloatingActionButtonMenu",
    "FloatingToolbar",
    "IconButton",
    "LinearProgressIndicator",
    "LinearWavyProgressIndicator",
    "ListItem",
    "LoadingIndicator",
    "MATERIAL3_CATALOG",
    "MaterialDivider",
    "MaterialList",
    "MaterialTheme",
    "Menu",
    "MenuItem",
    "NavigationBar",
    "NavigationDrawer",
    "NavigationItem",
    "NavigationRail",
    "RadioButton",
    "RangeSlider",
    "SearchBar",
    "SegmentedButton",
    "SegmentedButtonGroup",
    "SegmentedItem",
    "ShapeScale",
    "SideSheet",
    "Slider",
    "Snackbar",
    "SplitButton",
    "Switch",
    "Tab",
    "TabItem",
    "Tabs",
    "TextField",
    "TimePicker",
    "Toolbar",
    "Tooltip",
    "TopAppBar",
    "Typography",
    "TypeStyle",
]
